# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

dist: trusty

warnings_are_errors: true

r:
  - release
  - devel

r_build_args: --no-build-vignettes

os:
  - linux

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

apt_packages:
  - libgeos-dev
  - libgeos-c1
  - libproj-dev
  - libgdal-dev
  - curl
  - qpdf
  - r-cran-rgdal
  - r-cran-rgeos

before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get --yes --force-yes update -qq; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install python-gdal; fi;

r_packages:
  - covr
  - rmarkdown
  - testthat

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
